/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ExistingPhotosTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ExistingUploadsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MediaConvertComplete": {
      "name": string
      "type": "sst.aws.Function"
    }
    "PreviewsCdn": {
      "type": "sst.aws.Router"
      "url": string
    }
    "ProcessHeic": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Site": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SubmitMediaConvert": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}